contact_links:
  - name: Nokogiri Discussion Board
    url: https://github.com/sparklemotion/nokogiri/discussions
    about: Start a thread about a new feature idea, read the RFCs, ask and answer general questions.
